import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./css/globals.css";
import { ContextProvider } from "@/components/context/ContextProvider";
import { ReactFlowProvider } from "@xyflow/react";

const inter = Inter({ 
  subsets: ["latin"] 
});

export const metadata: Metadata = {
  title: "NN",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${inter.className} h-full antialiased`}
    >
      <body className="dark min-h-full flex flex-col">
        <ReactFlowProvider>
          <ContextProvider>
            {children}
          </ContextProvider>
        </ReactFlowProvider>
      </body>
    </html>
  );
}
